### ISSUE TITLE
HostObjectType and .NET Core

### ISSUE THREAD

**Issue by lcnandre** [ashmind/mirrorsharp#101]
I've noticed that a new `AspNetCore.Demo` project was added and decided to give it a try. Works like expected out of the box, but when you set the host object type to a custom class this error shows up everywhere in CodeMirror (even simple things like `using System` are marked with this error):

> Type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.2.1.0'

I'm using the same project from #99 , which is currently working perfectly on Owin and running in a Windows Container. The problem is that because the container has to run .NET Framework, the image size sits around 6GB and I was hoping to change it to Linux and .NET Core, which will produce an image about 100-200MB big and improve integration with my other existing .NET Core services.

Here's how to reproduce the problem:
1. Create an arbitrary class inside `AspNetCore.Demo` project
2. Reference the assembly with `AddMetadataReferencesFromFiles` based on location of the `Startup` class
3. Set the new class as the host object type on `SetOptionsFromClientExtension`
4. Run it and try writing some simple script on CodeMirror

I understand that the support for .NET Core is still a preview here, but that's a realy annoying error and it's worth notifying you.

**Comment by ashmind** [comment]
Thanks for reporting!

I was able to make it work with this:
```csharp
app.UseMirrorSharp(new MirrorSharpOptions {
    SelfDebugEnabled = true,
    IncludeExceptionDetails = true,
    SetOptionsFromClient = new SetOptionsFromClientExtension()
}.SetupCSharp(
    o => o.AddMetadataReferencesFromFiles(GetAllReferencePaths().ToArray()))
);

private IEnumerable<string> GetAllReferencePaths() {
    var assembly = typeof(MyHostClass).Assembly;
    yield return assembly.Location;
    foreach (var name in assembly.GetReferencedAssemblies()) {
        yield return Assembly.Load(name).Location;
    }
}
```

However I'll keep this open to investigate if I can make it work without a manual step.
And please raise any other issues if you see them, overall ASP.NET Core version should be reasonably stable, at least no worse than the Owin one.

**Comment by haacked** [comment]
Unfortunately this doesn't work for me. I'm running .NET core code on a Mac and get the same error `Type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.2.1.0'`. It's not clear to me why it even thinks `Object` is defined in `System.Runtime`. That assembly doesn't exist in .NET core.

**Comment by haacked** [comment]
I created a [PR with a minimal demo](https://github.com/ashmind/mirrorsharp/pull/127) of the issue I'm running into. The PR write-up provides more details.

If you have time, would love some help understanding how to get this to work properly. I'll keep digging in the meanwhile.

**Comment by haacked** [comment]
Ok, I seem to have resolved it by doing the following:

```csharp
        static IEnumerable<string> GetAllReferencePaths() {
            var assemblyPath = Path.GetDirectoryName(typeof(object).Assembly.Location)
                               ?? throw new InvalidOperationException("Could not find the assembly for object.");
            yield return Path.Combine(assemblyPath, "mscorlib.dll");
            yield return Path.Combine(assemblyPath, "System.dll");
            yield return Path.Combine(assemblyPath, "System.Core.dll");
            yield return Path.Combine(assemblyPath, "System.Runtime.dll");
            var assembly = typeof(IScriptGlobals).Assembly;
            yield return assembly.Location;
            foreach (var name in assembly.GetReferencedAssemblies()) {
                yield return Assembly.Load(name).Location;
            }
        }
```

I stumbled onto this solution in [this blog post](http://smack0007.github.io/blog/2014/adding-assembly-references-in-roslyn.html) which I followed from https://stackoverflow.com/questions/23907305/roslyn-has-no-reference-to-system-runtime.

In particular this comment from @pilchie seems to explain the issue:

> It appears that you are referencing a PortableClassLibrary. Portable Class Libraries pick up some of the basic types (like object/string/etc) from "System.Runtime.dll". However, in the desktop framework these come from mscorlib.dll. When you use typeof(object).Assembly, you get Roslyn's own version of object. Since Roslyn is not built as Portable Class Libraries, that is the one from mscorlib, and doesn't match the identity of your other references.

**Comment by Pilchie** [comment]
Right.  Keep in mind that the runtime a compiler is *running on* has no relation to the runtime a compiler is *compiling for*. As an example, consider the days when the compiler was written in C++, and didn't run on .NET at all.

You really need to find the reference assemblies for the runtime you want to target, and add them.

**Comment by ashmind** [comment]
Thanks everyone -- I am cleaning up the issues a bit, and since this one is improved by the PR above, I think it's OK to close.
Please re-raise a separate question if you see a specific problem not covered by the example.
