### ISSUE TITLE
Demo project no code completion, highlighting and so on

### ISSUE THREAD

**Issue by acolledge** [ashmind/mirrorsharp#103]
Using the demo project again supplied in the repo. When it runs up the textarea has no code completion, highlight etc. 

Unlike the test cases (Tests.Shared) the MirrorSharpOptions in the startup.cs does not call SetupCSharp. Isn't this required?

I updated the startup method to include a call to the method (as i don't have core 2.1 installed i changed the path to 2.2) but no success on getting the main features to work with chrome. 

Maybe i need to install core 2.1 as 2.2 is missing features? Seems wrong.

Here is the updated code in Startup.cs.

 MirrorSharpOptions option = new MirrorSharpOptions {
       SelfDebugEnabled = true,
       IncludeExceptionDetails = true,
       SetOptionsFromClient = new SetOptionsFromClientExtension()
};

option.SetupCSharp(c => {
c.MetadataReferences = ImmutableList<MetadataReference>.Empty;
c.AddMetadataReferencesFromFiles(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles)+@"\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.2.0\ref\netcoreapp2.2\System.Runtime.dll");});

app.UseMirrorSharp(option);

Anyway the control looks like it has a lot of promise and ill try and get it working to demo the team

**Comment by ashmind** [comment]
It should work out of the box (well, ASP.NET Core support is new, so might not).

What does the browser console say?
You might need to run `npm install` under the AspNetCore.Demo/wwwroot folder.

**Comment by acolledge** [comment]
Hi thanks for the response,

Looking at the browser console (ctrl+shift+j in chrome) it reports a lot of 

Failed to load resource: the server responded with a status of 404 (Not Found) for Mirrorsharp.css

So next I ran npm install using node.js console under the root folder and it still doesn't work but there are a lot less 404 errors. error log reads:

mirrorsharp.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
mirrorsharp.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
mirrorsharp.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
(index):92 Uncaught ReferenceError: mirrorsharp is not defined
    at (index):92
(anonymous) @ (index):92
:63675/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
mirrorsharp.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by ashmind** [comment]
Hmm, right, forgot that.
Try running 
```
npm install
npm run build
```
under `WebAssets`, then refresh the page.

**Comment by ashmind** [comment]
I'll update the docs when I have some time.

**Comment by acolledge** [comment]
Great that worked. To summarise:
 
1. Run NPM install under the wwwroot folder using node.js
2. Run NPM install under the WebAssests folder using node.js
3. Run npm run build under the WebAssests folder using node.js
