### ISSUE TITLE
What is SelfDebugEnabled?

### ISSUE THREAD

**Issue by FortuneN** [ashmind/mirrorsharp#109]

**Comment by ashmind** [comment]
This is a setting that enables `Shift-Ctrl-Y` to report all recent server interactions and client state changes in browser console. This is useful when debugging MirrorSharp state issues, but has performance implications (and maybe memory leaks) if enabled during normal work.

**Comment by ashmind** [comment]
Closing as answered, but I can reopen if you have further questions.
