### ISSUE TITLE
Mirrorsharp accepts ALL web sockets

### ISSUE THREAD

**Issue by FortuneN** [ashmind/mirrorsharp#110]
Should it not accept only those addressed to it?

https://github.com/ashmind/mirrorsharp/blob/master/AspNetCore/Internal/Middleware.cs

        public Task InvokeAsync(HttpContext context) {
            if (!context.WebSockets.IsWebSocketRequest)
                return _next(context);

            return StartWebSocketLoopAsync(context);
        }

[PULL REQUEST] https://github.com/ashmind/mirrorsharp/pull/111

**Comment by ashmind** [comment]
Yep that's a bug -- thanks for the PR! I'll discuss further in the PR.

**Comment by ashmind** [comment]
Decided to go for a different approach here (as described in the PR comment).
If you upgrade to 2.1 and switch from `UseMirrorSharp` to `MapMirrorSharp`, the accepted URLs should work correctly.

I am going to release Endpoint Routing support as v3 as it require ASP.NET Core upgrade.

**Comment by ashmind** [comment]
Closing since this should be resolved now, can reopen later if something still does not work.
