### ISSUE TITLE
Fallback behavior for unknown languages

### ISSUE THREAD

**Issue by haacked** [ashmind/mirrorsharp#128]
Is there a way to turn off the compilation errors when an unknown language is selected?

Here's the scenario: I have an editor where people can choose C#, Python, and JavaScript. If they choose C#, I want them to get that rich Roslyn experience. If they choose Python or JavaScript, I want the editor to behave like a standard CodeMirror instance.

Is there a way I can turn that behavior on and off? Maybe by turning off the socket or some other means?

**Comment by haacked** [comment]
> But I might be missing some disadvantages

The main thing is I'd like them to be able to switch languages without having to reload the page.

**Comment by ashmind** [comment]
That should work if you destroy the mirrosharp instance using `destroy`.
You can even tell it to keep the CodeMirror around.

That's similar to what SharpLab does when you switch Roslyn branches and it restarts the connection:
https://github.com/ashmind/SharpLab/blob/main/source/WebApp/components/app-code-edit-stable.ts#L69-L76

**Comment by haacked** [comment]
Ah, very cool! Thanks!
