### ISSUE TITLE
Bug in tooltip placement when browser is scrolled

### ISSUE THREAD

**Issue by haacked** [ashmind/mirrorsharp#133]
When you have an editor embedded in a web page that is scrollable, the tooltip is not placed correctly when scrolled. It seems to be positioned to a fixed coordinate plane and not the editor's coordinate plane.

See the screenshot to see what I mean:

![Screen Shot 2020-08-26 at 10 47 51 AM](https://user-images.githubusercontent.com/19977/91338442-caf7e180-e789-11ea-98d5-a5282ca335f2.png)

I was able to reproduce this in `AspNetCore.Demo` by removing this line in the `app.less` file:

```css
html, body { width: 100%; height: 100%; }
```

And then I added a text area below the editor so I could make the page scrollable.

**Comment by ashmind** [comment]
Good catch, thanks for reporting! I'll see what I can do, but seems solvable.

**Comment by ashmind** [comment]
I pushed a potential fix, should be in `mirrorsharp@2.0.1` on npm once build passes.

**Comment by haacked** [comment]
@ashmind I tried it out and seems to work great! 👍
