### ISSUE TITLE
CM6: Signature help

### ISSUE THREAD

**Issue by ashmind** [ashmind/mirrorsharp#152]

**Comment by JavadBahmaniKalleh** [comment]
hi,
i want use this project in my .net core 5 project and i do not how to use that, readme did not help me.
 please help me for use that!
thanks .

**Comment by ashmind** [comment]
@JavadBahmaniKalleh Thanks for asking! I would be happy to answer a specific question if that helps (but please raise it as a separate issue or discussion).
