### ISSUE TITLE
Is this a caching problem?

### ISSUE THREAD

**Issue by Sicos1977** [ashmind/mirrorsharp#186]
When I type something in MirrorSharp and use CTRL + Z to undo that and fix it MirrorSharp still's keep complaining about the error I made but it is already fixed. Is this somekind of caching problem and is there a way to solve this?

![image](https://user-images.githubusercontent.com/6692947/173019882-45b5657f-4629-4f4c-993b-0a2a8e259f25.png)

In the example above it is complaining about 'e' but I already fixed that.

**Comment by ashmind** [comment]
Thanks for reporting. Hmm, I would expect it is a bug in how undo is sent to the server -- I'll have to investigate.

**Comment by Sicos1977** [comment]
I don't know if it makes any difference but I'm using MirrorSharp on the .net 4.8 framework with ASP.NET webforms (yes I know this is old technology :-) )

**Comment by Sicos1977** [comment]
Also get it when I type to fast :-)

![image](https://user-images.githubusercontent.com/6692947/173029755-42367b66-fdf5-4790-9cb9-5e7c7be69356.png)

**Comment by Sicos1977** [comment]
I also can break everything by just selection a large portion of code, delete it paste it back, delete it again and past it back again. For some reason then all code editing features are broken.

The weird thing is that I don't see any errors anywhere, not in the Chrome console or on the server. It just stops working.

**Comment by Sicos1977** [comment]
I did some more test and inspected the object in Chrome and in this example I see something different in the "code behind" then what I see on the screen. This also explains why Roslyn is complaining the code is not correct.

In this a problem I have to look into in codemirror itself or is this a problem combination between codemirror and mirrorsharp?


![image](https://user-images.githubusercontent.com/6692947/178759725-e68bdb74-543a-4019-b368-b7f69da877df.png)

**Comment by Sicos1977** [comment]
![image](https://user-images.githubusercontent.com/6692947/178915119-d9dbcf70-edbb-4c66-9963-61c9206ac797.png)

**Comment by Sicos1977** [comment]
Any change that this gets fixed because it is sometimes very annoying that mirrorsharp is complaining that something is wrong in the code when it isn't

**Comment by Sicos1977** [comment]
Most of the time the problem occurs after just typing .. e.g. the var keyword --> mirrorsharp is suggestion sometime wrong --> I undo it and then this happens.

![image](https://user-images.githubusercontent.com/6692947/178930183-c785514a-6e16-4dd4-86d9-26e070fdcc35.png)


![image](https://user-images.githubusercontent.com/6692947/178930070-c1f82ad7-8932-4d99-820e-d92cc7aae580.png)

**Comment by Sicos1977** [comment]
I think I solved the problem by modifying the hinter.js file like this (I suck in javascript so don't blame me for doing something very stupid :-) )

I added a `var timeouts = [];` array to the `Hinter` class 

Changed this method

```js
    this[_Hinter_getHints] = (list, start) => {
      const prefix = this[_Hinter_cm].getRange(start, this[_Hinter_cm].getCursor());

      if (prefix.length > 0) {
        const regexp = new RegExp('^' + prefix.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&'), 'i'); // eslint-disable-next-line @typescript-eslint/no-non-null-assertion

        list = list.filter((item, index) => this[_Hinter_hasSuggestion] && index === 0 || regexp.test(item.text));
        if (this[_Hinter_hasSuggestion] && list.length === 1) list = [];
      }

      if (!this[_Hinter_hasSuggestion]) {
        // does not seem like I can use selectedHint here, as it does not force the scroll
        const selectedIndex = this[_Hinter_indexOfItemWithMaxPriority](list);

        if (selectedIndex > 0) timeouts.push(setTimeout(() => this[_Hinter_getActiveCompletion]()?.widget?.changeActive(selectedIndex), 0));
      }

      const result = {
        from: start,
        list
      };
      CodeMirror.on(result, 'select', this[_Hinter_loadInfo]);
      return result;
    };
```

And this method

```js
this[_Hinter_loadInfo] = (item, element) => {
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
      this[_Hinter_selected] = {
        item,
        index: item[indexInListKey],
        element
      };
       
	   //if (this[_Hinter_infoLoadTimer]) clearTimeout(this[_Hinter_infoLoadTimer]);

	  for (var i=0; i<timeouts.length; i++) {
		clearTimeout(timeouts[i]);
		timeouts = [];
	  }

      if (item[cachedInfoKey]) {
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        this[_Hinter_showInfoTip](this[_Hinter_selected].index, item[cachedInfoKey]);
      }

      this[_Hinter_infoLoadTimer] = setTimeout(() => {
        if (this[_Hinter_selected]) {
          // eslint-disable-next-line @typescript-eslint/no-floating-promises
          this[_Hinter_connection].sendCompletionState('info', this[_Hinter_selected].index);
        }

		timeouts.push(this[_Hinter_infoLoadTimer]);

        //if (this[_Hinter_infoLoadTimer]) clearTimeout(this[_Hinter_infoLoadTimer]);
      }, 300);
    };
```

**Comment by Sicos1977** [comment]
Uncaught Error: Unexpected undefined value at completion info index.
    at ensureDefined (ensure-defined.js:4:15)
    at Connection.sendCompletionState (connection.js:173:19)
    at hinter.js:94:48

**Comment by Sicos1977** [comment]
Can you (or somebody else) please give an answer so that I'm not talking to a black hole?

I logged the messages to the console that I get back from mirrorsharp and that still thinks there is something different on the screen then there is really there.

This is what I see
![image](https://user-images.githubusercontent.com/6692947/179176918-c1d42182-2644-42b4-ad08-a471392f2fa0.png)

This is what I see in the html elements
![image](https://user-images.githubusercontent.com/6692947/179177155-7838a471-b128-42a3-a328-2e189a1078a8.png)

And this is what the slowupdate process is thinking
![image](https://user-images.githubusercontent.com/6692947/179177084-a2940522-e841-4326-8aa6-c1b88274af87.png)

**Comment by Sicos1977** [comment]
I think I got it solved by removing this code from the `editor.js` file and the method `this[editorOnCodeMirrorChanges] = (_, changes) => {`

When typing to quick or moving to quick around in CodeMirror the server gets lots in where you are editing. After removing this code I don't have any problems anymore without weird suggestions

```javascript
                /*if (cursorIndex === start + 1 && text.length === 1 && !this[editorChangesAreFromServer]) {
                    if (length > 0) {
                        // eslint-disable-next-line @typescript-eslint/no-floating-promises
                        this[editorConnection].sendReplaceText(start, length, "", cursorIndex - 1);
                    } // eslint-disable-next-line @typescript-eslint/no-floating-promises

                    this[editorConnection].sendTypeChar(text);
					
                } else {*/
```

**Comment by Sicos1977** [comment]
Only now the tooltip window seems to be broken.

**Comment by Sicos1977** [comment]
Any updates on this?

**Comment by Sicos1977** [comment]
This is solved
