### ISSUE TITLE
Show Quick Info when hovering over any symbol in the document

### ISSUE THREAD

**Issue by SLaks** [ashmind/mirrorsharp#29]
...like VS does.

This may not be practical for RPC reasons; you'd need to either fetch symbols for the entire tree as it changes (too much work) or fetch symbols on hover (maybe too slow?).

The best way to implement this is to rewrite http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Shared/Extensions/ClassificationExtensions.cs,73 to generate HTML instead of WPF `TextBlock`s, then inject the subclasses of http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Intellisense/QuickInfo/Providers/AbstractQuickInfoProvider.cs,5fa67eed62fb3e25,references.

But that would require working with lots of Roslyn internals, and stubbing parts of the WPF editors.

**Comment by ashmind** [comment]
Thanks -- this is something I plan to do in #10, so I'll close this one and track it there.
