### ISSUE TITLE
Pre-select completion items

### ISSUE THREAD

**Issue by SLaks** [ashmind/mirrorsharp#34]
...like VS does.
For example, in a context that expects an enum.

This is driven by http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionItemRules.cs,66

**Comment by ashmind** [comment]
@SLaks Thanks, can you please give an example snippet (a context and what gets selected by VS)?

**Comment by SLaks** [comment]
Typing `new DateTime().DayOfWeek = ` will preselect `DayOfWeek`.
`Environment.GetEnvironmentVariable("a", ` will preselect `EnvironmentVariableTarget`.

Note that these have different commit characters.

**Comment by SLaks** [comment]
You should not need to reimplement this; the Completion APIs expose this for you.

**Comment by SLaks** [comment]
If you're using the latest Roslyn bits, there is also a more-general target type preselection; see https://github.com/dotnet/roslyn/pull/6878

**Comment by ashmind** [comment]
@SLaks Thanks! I'll take a look.
