### ISSUE TITLE
Don't pre-select completions in lambda context

### ISSUE THREAD

**Issue by SLaks** [ashmind/mirrorsharp#35]
If I type `Action<int> x = `, you should show a completion list, but don't select or auto-commit any completion until I press Tab or up/down.
Visual Studio calls this Suggestion Mode.

To detect, check whether [`SuggestionModeItem`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionList.cs,1a8ac1833e3623eb) is null.

http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Intellisense/Completion/Controller.Session_ComputeModel.cs,109

**Comment by ashmind** [comment]
@SLaks Interesting, do you know why this exists?

**Comment by SLaks** [comment]
Because you might be typing the parameter name of a lambda, which will not match any completions.
IOW, typing `.Select(s =>` should not change `s` to `System` when you press space.
