### ISSUE TITLE
Load XML Doc Comments

### ISSUE THREAD

**Issue by SLaks** [ashmind/mirrorsharp#46]
You should show descriptions from XML doc comments, in completion tooltips (#45), Quick Info (#10), and Signature Help.

You'll need to pass http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Utilities/Documentation/XmlDocumentationProvider.cs,44 to your MetadataReferences

You can fetch the XML doc comments from Reference Assemblies; see https://github.com/SLaks/VSEmbed/blob/master/VSEmbed.Roslyn/EditorWorkspace.cs#L111-L114

**Comment by ashmind** [comment]
Thanks for the research! For now I'll schedule this to 1.1 same as #9, but there is not much work left in milestone 0.9 so should be reasonably soon.

**Comment by ashmind** [comment]
- [x] Quick info
- [x] Completion tooltips
- [ ] Signature help - #95

Done for everything except signature help, going to close this and track signature help separately.
