### ISSUE TITLE
How do i add custom DLLs (Or any other other DLLs outside of 'System' and 'Microsoft')

### ISSUE THREAD

**Issue by FortuneN** [ashmind/mirrorsharp#81]
THANK YOU for making this available!!! (and i certainly would like to buy you a beer)

I wish to ask how i can add 'other' DLLs so they appear in the intellisense.

**Comment by FortuneN** [comment]
Done! It works!!! THANK YOU! THANK YOU!
I am following you and if you ever publish a "Buy Me A Beer" i'll be there!!

**Comment by ashmind** [comment]
Thanks! Glad to see it being useful.
