### ISSUE TITLE
Ability to add MetadataReferences after load (i.e. not having restart application)

### ISSUE THREAD

**Issue by FortuneN** [ashmind/mirrorsharp#83]
Perhaps we can have the ability to 'add' or 'remove' MetadataReferences after the owin initialization.

**Comment by ashmind** [comment]
What triggers add/remove in your use case -- client or server?  
If client, it should be possible to implement this using existing extensibility, I can give an example.

**Comment by FortuneN** [comment]
Please do give an example.
If that level of control is available client side it would be awesome to be able to isolate one 'reference pool' from the next for example

**Comment by FortuneN** [comment]
I've integrated this and it works. Thank you again
