### ISSUE TITLE
Show XML doc comments in signature help

### ISSUE THREAD

**Issue by ashmind** [ashmind/mirrorsharp#95]
Split from #46.

**Comment by haacked** [comment]
Just curious what this entails and if there's any plans for this soon. :smile:

**Comment by ashmind** [comment]
Hmm, good question. I don't think it's very complicated from what I remember.

But not sure when I can take a look (trying some other side-project now).
I'll try to do soon, but no specific timeline.

**Comment by ashmind** [comment]
Decided to give at a go as it seemed straightforward enough:
![image](https://user-images.githubusercontent.com/166396/92305355-8d415700-efda-11ea-8c87-37fb937fadc2.png)

Requires Common `2.2.1-preview-01` and mirrosharp.js `2.0.2-preview-01`.
Note that neither will fail if other does not support it, they'll just not show it.

Note that I've noticed some issues with XML doc loading in AspNetCore.Demo and adjusted it accordingly -- I tested the scripting scenario, and it still works, so hopefully all is well.

**Comment by haacked** [comment]
Amazing! ✨ I'll try it out and let you know how it works.

**Comment by haacked** [comment]
Hmm, when I updated the NPM package to `2.0.2-preview-01` my local build starts to fail. It worked previously.

```
ERROR in ./assets/main/css/_index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '~mirrorsharp/mirrorsharp.css'
```

Any ideas?

**Comment by haacked** [comment]
Ah, it looks like it moved to `~mirrorsharp/css/mirrorsharp.css`.

**Comment by haacked** [comment]
Hmm, I wonder if something changed in the way you build it because I also get an error when I try to import mirrorsharp in my code.

```js
import mirrorsharp from 'mirrorsharp';
```

> Module not found: Error: Can't resolve 'mirrorsharp'

I'm using WebPack. I'll dig into it.

**Comment by haacked** [comment]
Everything works fine with version `2.0.1`

**Comment by haacked** [comment]
I think I know what's going on.

Here's the `node_modules/mirrorsharp` directory in `2.0.1`
<img width="253" alt="Screen Shot 2020-09-08 at 9 50 31 AM" src="https://user-images.githubusercontent.com/19977/92505409-e535b480-f1b8-11ea-8af8-56cdb2630ac8.png">

And here it is for `2.0.2-preview-01`
<img width="355" alt="Screen Shot 2020-09-08 at 9 51 08 AM" src="https://user-images.githubusercontent.com/19977/92505415-e666e180-f1b8-11ea-8996-72824fcc7139.png">

**Comment by haacked** [comment]
So if I copy the contents of the dist folder and then clear out the `mirrorsharp` directory and copy in the contents of the `dist` folder, my project builds.

**Comment by ashmind** [comment]
Wow that's some bad packaging on my side.
Makes sense, it's the first one deployed using GtiHub Actions, so deployment pipeline is still a bit rough.

I'll take a look now.

**Comment by ashmind** [comment]
@haacked Please try again with `2.0.2-preview-02`.
Thanks for detailed issue report! Allowed me to react quickly (aside from the timezones).

**Comment by haacked** [comment]
Works like a charm! Thanks!

**Comment by haacked** [comment]
Might be nice to show how to get xml doc comments for your own referenced assemblies such as `IScriptGlobals`. I can probably do that later as I have it working on my machine.

One problem I did run into is doc comments don't seem to be working for `List<T>`. For example, if I do this:

```csharp
var list = new List<string>();
list.
```

I don't see comments for `list.Add` but I do see comments for some extension methods.

I stepped through the code and verified that `System.Collections.xml` is copied to the right place (the `xmldocs` folder) and that we're resolving it.

It's really weird because everything else works fine such as `string.` methods. Are you getting the same thing?

**Comment by ashmind** [comment]
Interesting, thanks for reporting! I think it's a limitation of xml files (from SDK) not quite matching dll structure (from runtime), however I can certainly try to apply some hacks... Since it's a demo I don't feel that bad about workarounds, I'll try something.

**Comment by ashmind** [comment]
Decided not to do workarounds and use reference assemblies properly instead (well, copy of them), seems to be working ok.

**Comment by haacked** [comment]
This worked great!

Got another question (this could be a separate issue). Right now `mirrorsharp` will show there are overloads, but there doesn't seem to be any way to iterate over them. Probably a limitation of `codemirror` eh?

![Screen Shot 2020-09-10 at 12 29 38 PM](https://user-images.githubusercontent.com/19977/92791472-8eb7aa00-f361-11ea-8fd1-f2e9b69a3f3c.png)

**Comment by ashmind** [comment]
Hmm -- I tried to mirror Visual Studio behavior there, but does Visual Studio have some shortcut to iterate them within autocomplete dialog? (I know you can once you starting to write the call, but then I just all overloads for that anyway)

**Comment by ashmind** [comment]
In VS I can iterate here
![image](https://user-images.githubusercontent.com/166396/92865633-aa4ead80-f452-11ea-9b8f-c5b6747a1438.png)

But in mirrorsharp I just show all at once:
![image](https://user-images.githubusercontent.com/166396/92866694-f51cf500-f453-11ea-9e4c-05c32bb2abd2.png)

I don't mind changing that to iterate, just a bit more work required, so probably not soon.

**Comment by haacked** [comment]
Is that a setting? I don't see the overloads?

<img width="1130" alt="Screen Shot 2020-09-11 at 7 59 53 AM" src="https://user-images.githubusercontent.com/19977/92941153-da6f5f80-f404-11ea-96b9-31633167b6fe.png">

**Comment by haacked** [comment]
Oh, nevermind. I have to type `string.Compare(` to see it. Works fine for me. :smile:

**Comment by haacked** [comment]
I think you can close this issue!

**Comment by RhondaMorrison420** [comment]
I need my account to be active
