### ISSUE TITLE
Any support for globals?

### ISSUE THREAD

**Issue by brutto-avt** [ashmind/mirrorsharp#99]
Hello. I need to expose to CodeMirror an object on my server. Say I have a class like that:

```csharp
public class MyClass {
  public int myProp { get; set; }
}
```

I can set the host object type with:

```csharp
session.Roslyn.SetScriptMode (true, typeof (MyClass));
```

However, I don't see any option to inject an "host object value" as an instance of `MyClass` to the session, like it says on [Roslyn docs](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples#parameter). Is there any way to do that, so when I type `myProp = 5;` CodeMirror recognizes `myProp` as a property of the host object type?

PS: turning `MyClass` into static is not an option.

**Comment by ashmind** [comment]
The difference here is between the compilation and execution. For compilation, it should be enough to do `SetupCSharp(o => o.SetScriptMode(hostObjectType: typeof(MyClass)))` or `session.Roslyn.SetScriptMode (true, typeof(MyClass));` to see `myProp = 5;` being suggested by Intellisense and work correctly.

Execution is where you want to provide the specific instance, but mirrorsharp does not manage execution. Depending on your use case you can get compilation from mirrorsharp session and call `Emit()`, or re-parse and compile later if you want to run this separately from mirrorsharp session.

I don't remember what Roslyn scripts compile to, but the compiled script class should have a way to specify global instance somehow -- try saving it into a dll and checking constructor args and properties.

**Comment by brutto-avt** [comment]
I have created a repository to show my problem: https://github.com/brutto-avt/mirrosharp-test

* It's a minimalistic version of the exact same issue I'm facing on my application
* It's a Owin.SelfHost project targeting net4.6.1
* Tried both `mso.SetupCSharp(o => o.SetScriptMode(hostObjectType: typeof(MyClass)))` and `session.Roslyn.SetScriptMode(true, typeof(MyClass));` with no luck
* The only differences from [your demo](https://github.com/ashmind/mirrorsharp/blob/master/Owin.Demo/Startup.cs) are the `mscorlib.dll` reference (is that mandatory?) and the `assembly` decorator.
